language: cpp # node_js is not supported yet on osx
compiler: gcc
sudo: false

os:
  - linux
  - osx

env:
  matrix:
    - export NODE_VERSION="6"
    - export NODE_VERSION="7"
    - export NODE_VERSION="8"
    - export NODE_VERSION="9"
    - export NODE_VERSION="10"

matrix:
  fast-finish: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libbluetooth-dev

before_install:
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm config set python `which python`
  - gcc --version
  - g++ --version
  - npm --version
  - node --version

script:
  - npm install
  - node ./test/index.js

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules

